quarkus.application.name=dnotam-publisher
quarkus.application.version=1.0.0

quarkus.otel.resource.attributes=service.namespace=nav-portugal,deployment.environment=${DEPLOYMENT_ENV:local}
quarkus.otel.propagators=tracecontext,baggage
quarkus.otel.exporter.otlp.endpoint=${OTLP_ENDPOINT:http://tempo:4317}
quarkus.otel.instrument.messaging=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId} spanId=%X{spanId} [%c{2.}] (%t) %s%e%n

quarkus.otel.logs.enabled=true
quarkus.otel.exporter.otlp.logs.endpoint=${LOKI_OTLP_ENDPOINT:http://loki:3100/otlp}
quarkus.otel.exporter.otlp.logs.protocol=http/protobuf

amqp-host=${AMQP_HOST:artemis}
amqp-port=${AMQP_PORT:5672}
amqp-username=${AMQP_USER:admin}
amqp-password=${AMQP_PASSWORD:admin}

mp.messaging.outgoing.dnotam-out.connector=smallrye-amqp
mp.messaging.outgoing.dnotam-out.address=swim.dnotam.updates
mp.messaging.outgoing.dnotam-out.durable=true
mp.messaging.outgoing.dnotam-out.tracing-enabled=true
