server:
  http_listen_port: 3200
  grpc_listen_port: 9095

stream_over_http_enabled: true

live_store:
  max_trace_idle: 2s
  fail_on_high_lag: false

query_frontend:
  query_end_cutoff: 5s

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: swim-sfg
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://sfg-prometheus:9090/api/v1/write
        send_exemplars: true
  processor:
    service_graphs:
      dimensions:
        - service.name
    span_metrics:
      dimensions:
        - service.name
        - span.kind

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
