FROM docker.io/eclipse-temurin:25-jre
WORKDIR /deployments
COPY target/quarkus-app/lib/ lib/
COPY target/quarkus-app/*.jar .
COPY target/quarkus-app/app/ app/
COPY target/quarkus-app/quarkus/ quarkus/
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser && chown -R appuser:appgroup /deployments
USER appuser
EXPOSE 8080
CMD ["java", "-jar", "quarkus-run.jar"]
