quarkus.application.name=eurocontrol-hub
quarkus.application.version=1.0.0

quarkus.otel.resource.attributes=service.namespace=swim-sfg,deployment.environment=${DEPLOYMENT_ENV:local}
quarkus.otel.exporter.otlp.endpoint=${OTLP_ENDPOINT:http://sfg-hub-tempo:4317}
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId} [%c{2.}] (%t) %s%e%n

quarkus.rest-client.tempo.url=${TEMPO_URL:http://sfg-hub-tempo:3200}
quarkus.rest-client.tempo.scope=jakarta.inject.Singleton
